### ISSUE TITLE
Posible Virus

### ISSUE THREAD

**Issue by therysin** [x0r19x91/010-k3yg3n#2]
Tested in a VM and there are no visible signs of anything happening when the program is launched. In virus total, the result was 28/67. https://www.virustotal.com/#/file/7ee7deebd55297111f64d700cda87865997b9ce9b9a9879482ec626ac5ce1515/detection
Edit:
Seems like the raw main.exe is fine. It's the one under release that's packed or something?

**Comment by x0r19x91** [comment]
Its not packed. Its pure assembly code

**Comment by therysin** [comment]
Any idea whats up with the false positives though?

**Comment by x0r19x91** [comment]
First of all there is no import table. All the necessary imports are done at runtime

**Comment by therysin** [comment]
It's really cool that this was written in assembly. Never actually written a full program in pure asm before. I'll close this issue, I just really didn't like the false positives, and got suspicious when nothing happened when I tried to launch, but that could have been windows defender or something in the VM. Good keygen.

**Comment by x0r19x91** [comment]
Thanks. Is it working ?

**Comment by x0r19x91** [comment]
I hope you liked it
